### ISSUE TITLE
enhancement use WITHOUT admin

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav-plugin-custom-css#4]
Please forgive me if this is not the right place.

Actually, this is not really an issue, more an enhancement request.

Would it be possible to describe how it would be possible to make a use of this plugin WITHOUT the admin panel?

I know that it is already possible to add a `file.css` in folder `customcss`.

I am interested in having inline css for critical path rendering matters which is not possible with the customcss folder method.

I have thinking also of the AddInlineCss method, but for a complex page, the data is too long and I was not able to have it working.

What I really would like is to have my css put in HEAD between <style> tags without spaces, well minified.

thanks in advance ☆

**Comment by flaviocopes** [comment]
Just saw this - you can set

```
enabled: true
css_inline: "some inline css"
```

in `user/config/plugins/custom-css.yaml`.

Minification will be provided by Grav's own assets pipeline/minification functionality.
