### ISSUE TITLE
Twig says ""Undefined index: path""

### ISSUE THREAD

**Issue by ThosG** [getgrav/grav-plugin-custom-css#5]
Using Twentyfifteen. Installed custom-css and set INline CSS to `.entry-content {font-size: 80%; }`

Twigsaid
`Whoops \ Exception \ ErrorException (E_NOTICE)
Undefined index: path
`

The problem seems to be here:
`        foreach($this->config->get('plugins.custom-css.css_files', []) as $file) {
            $this->grav['assets']->addCss($file['path'], isset($file['priority']) ? $file['priority'] : null);
        }
`

**Comment by flaviocopes** [comment]
What's in your `user/config/plugins/custom-css.yaml` file?

**Comment by ThosG** [comment]
I left the yaml alone. I’m sorry, but I abandoned the TwentyFifteen theme, after finding I couldn’t modify the font size because of a bug in the custom.css plugin. It looked to me as though the bug was independent of the theme. So I can’t do any testing. Very sorry if I was wrong about that., but I needed to get on. Complete forgiveness if that means you can’t do anything about the bug until someone else finds it.

Thomas Green
