### ISSUE TITLE
loading a css for a specific page/template

### ISSUE THREAD

**Issue by JOduMonT** [getgrav/grav-plugin-custom-css#9]
Hello;

I'm sorry to open this issue here, but I wasn't sure where to ask and it seams to be the most reverent place for it.

So;
I'm able to make a if this option in the theme is load this css
but I don't understand how to do the same thing with
if I use this template file load this css.

such as an example
this is works

> {% if config.theme.navbar_position == 'fixed-top' %}{% do assets.add('theme://css/navbar-fixed-top.css',98) %}{% endif %}

I would like something like this works too

> {% if config.template.cover %}{% do assets.add('theme://css/cover.css',98) %}{% endif %}

**Comment by rhukster** [comment]
Thi sis not related to custom css plugin
